package hibernate;
// Generated Feb 20, 2017 3:21:26 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ComplainTable generated by hbm2java
 */
@Entity
@Table(name="complain_table"
    ,catalog="ohsdb"
)
public class ComplainTable  implements java.io.Serializable {


     private Integer complainId;
     private String username;
     private String complainTitle;
     private String complainDescription;
     private String venue;
     private String imageName;
     private String status;

   

    public ComplainTable() {
    }

    public ComplainTable(String username, String complainTitle, String complainDescription, String venue, String imageName,String status) {
       this.username = username;
       this.complainTitle = complainTitle;
       this.complainDescription = complainDescription;
       this.venue = venue;
       this.imageName = imageName;
       this.status=status;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="complain_id", nullable=false)
    public Integer getComplainId() {
        return this.complainId;
    }
    
    public void setComplainId(Integer complainId) {
        this.complainId = complainId;
    }

    
    @Column(name="username", nullable=false, length=54)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="complain_title", nullable=false, length=54)
    public String getComplainTitle() {
        return this.complainTitle;
    }
    
    public void setComplainTitle(String complainTitle) {
        this.complainTitle = complainTitle;
    }

    
    @Column(name="complain_description", nullable=false, length=500)
    public String getComplainDescription() {
        return this.complainDescription;
    }
    
    public void setComplainDescription(String complainDescription) {
        this.complainDescription = complainDescription;
    }

    
    @Column(name="venue", nullable=false, length=54)
    public String getVenue() {
        return this.venue;
    }
    
    public void setVenue(String venue) {
        this.venue = venue;
    }

    
    @Column(name="image_name", nullable=false, length=200)
    public String getImageName() {
        return this.imageName;
    }
    
    public void setImageName(String imageName) {
        this.imageName = imageName;
    }


    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

}


